// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvzttkhofdovdmqlwcxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2enR0a2hvZmRvdmRtcWx3Y3hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTY3MjYsImV4cCI6MjA3MDA3MjcyNn0.NgI1V9EVCwaUKSGnOySSoI6px9RoP5LMw_T9RNSyQRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});